#!/usr/bin/perl -w

use Manager;
use UniLang::Agent::Agent;
use UniLang::Util::Message;

$UNIVERSAL::agent = UniLang::Agent::Agent->new
  (Name => "Manager",
   ReceiveHandler => \&Receive);
$UNIVERSAL::agent->DoNotDaemonize(1);

$UNIVERSAL::manager = Manager->new();

sub Receive {
  my %args = @_;
  $UNIVERSAL::manager->ProcessMessage
    (Message => $args{Message});
}

$UNIVERSAL::manager->Execute;
