#!/usr/bin/perl -w

# /var/lib/myfrdcsa/codebases/internal/manager/scripts/what-to-do.flr

# this suggests things to do

my @list = (
	    ["<REDACTED>"],
	   );

# query habituals from freekbs

print $list[int rand $#list][0]."\n";
