#!/bin/sh

ifconfig eth1 10.0.0.1
echo 1 > /proc/sys/net/ipv4/ip_forward
iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE

# modify iptables to be --source 10.0.0.2
# must be run at boot up

# other machine
# set resolv.conf
# ifconfig eth0 10.0.0.2 up
# route add default gw 10.0.0.1

# network IP of that machine is 128.2.213.59

# iptables -t nat -A PREROUTING -i eth1 -d 128.2.213.59/22 -j DNAT --to 10.0.0.2